### ISSUE TITLE
POST requests to /api/posts are being redirected to GET /

### ISSUE THREAD

**Issue by kotoshii** [Serezon/stokk#1]
![image](https://user-images.githubusercontent.com/40234487/83354535-fffac080-a361-11ea-8b9e-0d94638f7724.png)
![image](https://user-images.githubusercontent.com/40234487/83354550-1a349e80-a362-11ea-83ab-c514451cff4e.png)

**Comment by Serezon** [comment]
Спробуй вказати у запиті хедер "Accept": "application/json"

**Comment by kotoshii** [comment]
> Спробуй вказати у запиті хедер "Accept": "application/json"

Дякую. Тепер працює.
